#ifndef __TIMEKEEPER_DEFINITIONS__
#define __TIMEKEEPER_DEFINITIONS__


#define REGISTER_TRACER 'A'
#define GETTIMEPID 'B'
#define SYNC_AND_FREEZE 'C'
#define SET_NETDEVICE_OWNER 'D'
#define UPDATE_TRACER_PARAMS 'E'
#define PROGRESS  'F'
#define PROGRESS_N_ROUNDS	'G'

#define START_EXP 'H'
#define STOP_EXP 'I'

#define TRACER_RESULTS 'J'
#define INITIALIZE_EXP 'K'


#endif
